#############################################################################
# Makefile for building: calliope
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sat Aug 27 11:33:20 2011
# Project:  calliope.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile calliope.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mobi.cpp \
		page.cpp \
		element.cpp \
		main.cpp \
		bookdevice.cpp \
		parser.cpp \
		bookshelf.cpp \
		shelfscreen.cpp \
		pagebuttonbar.cpp moc_page.cpp \
		moc_shelfscreen.cpp \
		moc_pagebuttonbar.cpp
OBJECTS       = mobi.o \
		page.o \
		element.o \
		main.o \
		bookdevice.o \
		parser.o \
		bookshelf.o \
		shelfscreen.o \
		pagebuttonbar.o \
		moc_page.o \
		moc_shelfscreen.o \
		moc_pagebuttonbar.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		calliope.pro
QMAKE_TARGET  = calliope
DESTDIR       = 
TARGET        = calliope

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: calliope.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile calliope.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile calliope.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/calliope1.0.0 || $(MKDIR) .tmp/calliope1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/calliope1.0.0/ && $(COPY_FILE) --parents mobi.h page.h element.h bookdevice.h parser.h bookshelf.h shelfscreen.h pagebuttonbar.h .tmp/calliope1.0.0/ && $(COPY_FILE) --parents mobi.cpp page.cpp element.cpp main.cpp bookdevice.cpp parser.cpp bookshelf.cpp shelfscreen.cpp pagebuttonbar.cpp .tmp/calliope1.0.0/ && (cd `dirname .tmp/calliope1.0.0` && $(TAR) calliope1.0.0.tar calliope1.0.0 && $(COMPRESS) calliope1.0.0.tar) && $(MOVE) `dirname .tmp/calliope1.0.0`/calliope1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/calliope1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_page.cpp moc_shelfscreen.cpp moc_pagebuttonbar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_page.cpp moc_shelfscreen.cpp moc_pagebuttonbar.cpp
moc_page.cpp: element.h \
		page.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) page.h -o moc_page.cpp

moc_shelfscreen.cpp: bookshelf.h \
		mobi.h \
		shelfscreen.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) shelfscreen.h -o moc_shelfscreen.cpp

moc_pagebuttonbar.cpp: pagebuttonbar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) pagebuttonbar.h -o moc_pagebuttonbar.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

mobi.o: mobi.cpp mobi.h \
		bookdevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mobi.o mobi.cpp

page.o: page.cpp page.h \
		element.h \
		mobi.h \
		parser.h \
		shelfscreen.h \
		bookshelf.h \
		pagebuttonbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o page.o page.cpp

element.o: element.cpp element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o element.o element.cpp

main.o: main.cpp mobi.h \
		page.h \
		element.h \
		parser.h \
		bookdevice.h \
		bookshelf.h \
		shelfscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

bookdevice.o: bookdevice.cpp bookdevice.h \
		mobi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookdevice.o bookdevice.cpp

parser.o: parser.cpp parser.h \
		element.h \
		mobi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o parser.cpp

bookshelf.o: bookshelf.cpp bookshelf.h \
		mobi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookshelf.o bookshelf.cpp

shelfscreen.o: shelfscreen.cpp shelfscreen.h \
		bookshelf.h \
		mobi.h \
		page.h \
		element.h \
		bookdevice.h \
		parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shelfscreen.o shelfscreen.cpp

pagebuttonbar.o: pagebuttonbar.cpp pagebuttonbar.h \
		page.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pagebuttonbar.o pagebuttonbar.cpp

moc_page.o: moc_page.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_page.o moc_page.cpp

moc_shelfscreen.o: moc_shelfscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_shelfscreen.o moc_shelfscreen.cpp

moc_pagebuttonbar.o: moc_pagebuttonbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pagebuttonbar.o moc_pagebuttonbar.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

